In [17]:
import re
from collections import defaultdict

In [32]:
def get_table_names(input_file, output_file):
    pattern = re.compile(
        r"INSERT INTO\s+(\[[^\]]+\]\.\[[^\]]+\])",
        re.IGNORECASE)
    table_names = []
    try:
        with open(input_file, 'r', encoding='utf-8') as input_file:
            # Sử dụng enumerate(..., 1) để lấy cả số dòng (bắt đầu từ 1) và nội dung
            for line in input_file:
                 # Sử dụng re.search() để tìm kiếm mẫu trong từng dòng
                match = pattern.search(line)
                
                # Nếu tìm thấy mẫu
                if match:
                    # match.group(0) sẽ là toàn bộ chuỗi khớp (vd: 'INSERT INTO  [dbo].[task_files]')
                    # match.group(1) sẽ là chuỗi trong cặp ngoặc đơn đầu tiên của pattern
                    table_name = match.group(1)
                    table_names.append(table_name)
                    print(f"  - Tìm thấy: {table_name} trong dòng: \"{line.strip()}\"")


        # Ghi kết quả thống kê này ra file
        unique_table_names = sorted(list(set(table_names)))
        with open(output_file, 'w', encoding='utf-8') as f_out:
            if unique_table_names:
                f_out.write(f"Thống kê {len(unique_table_names)} bảng được tìm thấy trong file '{input_sql_file}':\n\n")
                
                # Sắp xếp theo tên bảng để kết quả có thứ tự
                for table_name in sorted(unique_table_names):                    
                    f_out.write(f"{table_name};\n")
                    
            else:
                f_out.write(f"Không tìm thấy bảng nào.\n")

        print(f"Đã ghi thống kê chi tiết vào file '{output_file}'")

    except FileNotFoundError:
        print(f"Lỗi: Không tìm thấy file nguồn '{input_sql_file}'")
    except Exception as e:
        print(f"Đã xảy ra một lỗi không mong muốn: {e}")

In [21]:
def get_table_name_from_src(input_sql_file, output_insert_file):
    # Biểu thức chính quy để tìm chuỗi có dạng [schema].[table] theo sau "INSERT INTO"
    # re.IGNORECASE để không phân biệt chữ hoa/thường (bắt được cả INSERT INTO và insert into)
    # \s+ khớp với một hoặc nhiều khoảng trắng
    # (\[[^\]]+\]\.\[[^\]]+\]) là nhóm chúng ta muốn lấy (capturing group)
    pattern = re.compile(
        r"^Dòng\s+(\d+):\s*.*INSERT INTO\s+(\[[^\]]+\]\.\[[^\]]+\])",
        re.IGNORECASE)
    table_names = []
    try:
        with open(input_sql_file, 'r', encoding='utf-8') as input_sql_file:
            # Sử dụng enumerate(..., 1) để lấy cả số dòng (bắt đầu từ 1) và nội dung
            for line in input_sql_file:
                
                # Sử dụng re.search() để tìm kiếm mẫu trong từng dòng
                match = pattern.search(line)
                
                # Nếu tìm thấy mẫu
                if match:
                    # Nhóm 1 là số dòng
                    line_number = match.group(1)
                    # Nhóm 2 là tên bảng
                    table_name = match.group(2)
                    
                    # Thêm cặp kết quả vào danh sách
                    table_names.append((line_number, table_name))
                    print(f"  - OK: Dòng '{line_number}' -> Bảng '{table_name}'")

        # Giả sử 'results' là danh sách các cặp (số dòng, tên bảng) đã tìm được
        # Ví dụ: results = [('264994', '[dbo].[task_assignees]'), ('265996', '[dbo].[task_assignees]'), ('266998', '[dbo].[tasks]')]

        # Tạo một dictionary để nhóm các dòng theo tên bảng
        tables_with_lines = defaultdict(list)
        for line_number, table_name in table_names:
            tables_with_lines[table_name].append(line_number)

        # Kết quả của 'tables_with_lines' sẽ là:
        # {
        #   '[dbo].[task_assignees]': ['264994', '265996'],
        #   '[dbo].[tasks]': ['266998']
        # }

        # Ghi kết quả thống kê này ra file
        with open(output_insert_file, 'w', encoding='utf-8') as f_out:
            if tables_with_lines:
                f_out.write(f"Thống kê {len(tables_with_lines)} bảng được tìm thấy trong file '{input_sql_file}':\n\n")
                
                # Sắp xếp theo tên bảng để kết quả có thứ tự
                for table_name in sorted(tables_with_lines.keys()):
                    line_numbers = tables_with_lines[table_name]
                    # Nối các số dòng thành một chuỗi, cách nhau bởi dấu phẩy
                    lines_str = ', '.join(line_numbers)
                    
                    f_out.write(f"- Bảng: {table_name}\n")
                    f_out.write(f"  -> Xuất hiện ở các dòng: {lines_str}\n\n")
                    
            else:
                f_out.write(f"Không tìm thấy bảng nào.\n")

        print(f"Đã ghi thống kê chi tiết vào file '{output_insert_file}'")

    except FileNotFoundError:
        print(f"Lỗi: Không tìm thấy file nguồn '{input_sql_file}'")
    except Exception as e:
        print(f"Đã xảy ra một lỗi không mong muốn: {e}")

In [35]:
input_sql_file = 'insert_lines_of_PronaFlow_New_Sample_Data_EN.txt'

In [34]:
output_insert_file = 'table_names.txt'
get_table_name_from_src(input_sql_file, output_insert_file)

  - OK: Dòng '46' -> Bảng '[dbo].[users]'
  - OK: Dòng '88' -> Bảng '[dbo].[workspaces]'
  - OK: Dòng '338' -> Bảng '[dbo].[tags]'
  - OK: Dòng '1340' -> Bảng '[dbo].[tags]'
  - OK: Dòng '1848' -> Bảng '[dbo].[projects]'
  - OK: Dòng '2850' -> Bảng '[dbo].[projects]'
  - OK: Dòng '3852' -> Bảng '[dbo].[projects]'
  - OK: Dòng '4854' -> Bảng '[dbo].[projects]'
  - OK: Dòng '5677' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '6679' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '7681' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '8683' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '9685' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '10687' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '11689' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '12691' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '13693' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '14695' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '15697' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '16699' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '17701' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '18703' -> Bảng '[dbo].[project_members]'
  - OK: Dòng '18924' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '19926' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '20928' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '21930' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '22932' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '23934' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '24936' -> Bảng '[dbo].[project_tags]'
  - OK: Dòng '24985' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '25987' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '26989' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '27991' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '28993' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '29995' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '30997' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '31999' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '33001' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '34003' -> Bảng '[dbo].[task_lists]'
  - OK: Dòng '34516' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '35518' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '36520' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '37522' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '38524' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '39526' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '40528' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '41530' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '42532' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '43534' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '44536' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '45538' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '46540' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '47542' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '48544' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '49546' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '50548' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '51550' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '52552' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '53554' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '54556' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '55558' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '56560' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '57562' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '58564' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '59566' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '60568' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '61570' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '62572' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '63574' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '64576' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '65578' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '66580' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '67582' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '68584' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '69586' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '70588' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '71590' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '72592' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '73594' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '74596' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '75598' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '76600' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '77602' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '78604' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '79606' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '80608' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '81610' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '82612' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '83614' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '84616' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '85618' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '86620' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '87622' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '88624' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '89626' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '90628' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '91630' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '92632' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '93634' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '94636' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '95638' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '96640' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '97642' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '98644' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '99646' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '100648' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '101650' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '102652' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '103654' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '104656' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '105658' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '106660' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '107662' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '108664' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '109666' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '110668' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '111670' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '112672' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '113674' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '114676' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '115678' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '116680' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '117682' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '118684' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '119686' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '120688' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '121690' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '122692' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '123694' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '124696' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '125698' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '126700' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '127702' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '128704' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '129706' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '130708' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '131710' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '132712' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '133714' -> Bảng '[dbo].[tasks]'
  - OK: Dòng '133732' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '134734' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '135736' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '136738' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '137740' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '138742' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '139744' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '140746' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '141748' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '142750' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '143752' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '144754' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '145756' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '146758' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '147760' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '148762' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '149764' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '150766' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '151768' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '152770' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '153772' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '154774' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '155776' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '156778' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '157780' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '158782' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '159784' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '160786' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '161788' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '162790' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '163792' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '164794' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '165796' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '166798' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '167800' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '168802' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '169804' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '170806' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '171808' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '172810' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '173812' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '174814' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '175816' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '176818' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '177820' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '178822' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '179824' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '180826' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '181828' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '182830' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '183832' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '184834' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '185836' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '186838' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '187840' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '188842' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '189844' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '190846' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '191848' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '192850' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '193852' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '194854' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '195856' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '196858' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '197860' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '198862' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '199864' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '200866' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '201868' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '202870' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '203872' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '204874' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '205876' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '206878' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '207880' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '208882' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '209884' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '210886' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '211888' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '212890' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '213892' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '214894' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '215896' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '216898' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '217900' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '218902' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '219904' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '220906' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '221908' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '222910' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '223912' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '224914' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '225916' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '226918' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '227920' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '228922' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '229924' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '230926' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '231928' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '232930' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '233932' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '234934' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '235936' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '236938' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '237940' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '238942' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '239944' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '240946' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '241948' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '242950' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '243952' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '244954' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '245956' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '246958' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '247960' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '248962' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '249964' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '250966' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '251968' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '252970' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '253972' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '254974' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '255976' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '256978' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '257980' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '258982' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '259984' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '260986' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '261988' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '262990' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '263992' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '264994' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '265996' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '266998' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '268000' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '269002' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '270004' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '271006' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '272008' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '273010' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '274012' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '275014' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '276016' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '277018' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '278020' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '279022' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '280024' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '281026' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '282028' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '283030' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '284032' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '285034' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '286036' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '287038' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '288040' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '289042' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '290044' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '291046' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '292048' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '293050' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '294052' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '295054' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '296056' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '297058' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '298060' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '299062' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '300064' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '301066' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '302068' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '303070' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '304072' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '305074' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '306076' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '307078' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '308080' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '309082' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '310084' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '311086' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '312088' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '313090' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '314092' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '315094' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '316096' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '317098' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '318100' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '319102' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '320104' -> Bảng '[dbo].[task_assignees]'
  - OK: Dòng '320572' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '321574' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '322576' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '323578' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '324580' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '325582' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '326584' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '327586' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '328588' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '329590' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '330592' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '331594' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '332596' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '333598' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '334600' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '335602' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '336604' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '337606' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '338608' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '339610' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '340612' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '341614' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '342616' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '343618' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '344620' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '345622' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '346624' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '347626' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '348628' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '349630' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '350632' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '351634' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '352636' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '353638' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '354640' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '355642' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '356644' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '357646' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '358648' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '359650' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '360652' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '361654' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '362656' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '363658' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '364660' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '365662' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '366664' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '367666' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '368668' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '369670' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '370672' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '371674' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '372676' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '373678' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '374680' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '375682' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '376684' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '377686' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '378688' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '379690' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '380692' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '381694' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '382696' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '383698' -> Bảng '[dbo].[subtasks]'
  - OK: Dòng '384700' -> Bảng '[dbo].[subtasks]'

In [33]:
output_file = 'table_names_simple.txt'
get_table_names(input_sql_file, output_file)

  - Tìm thấy: [dbo].[users] trong dòng: "Dòng 46: INSERT INTO [dbo].[users] ([username], [email], [password_hash], [full_name], [bio], [role]) VALUES"
  - Tìm thấy: [dbo].[workspaces] trong dòng: "Dòng 88: INSERT INTO [dbo].[workspaces] ([owner_id], [name], [description]) VALUES"
  - Tìm thấy: [dbo].[tags] trong dòng: "Dòng 338: INSERT INTO [dbo].[tags] ([workspace_id], [name], [color_hex]) VALUES"
  - Tìm thấy: [dbo].[tags] trong dòng: "Dòng 1340: INSERT INTO [dbo].[tags] ([workspace_id], [name], [color_hex]) VALUES"
  - Tìm thấy: [dbo].[projects] trong dòng: "Dòng 1848: INSERT INTO [dbo].[projects] ([workspace_id], [name], [description], [status], [project_type], [start_date], [end_date], [is_archived]) VALUES"
  - Tìm thấy: [dbo].[projects] trong dòng: "Dòng 2850: INSERT INTO [dbo].[projects] ([workspace_id], [name], [description], [status], [project_type], [start_date], [end_date], [is_archived]) VALUES"
  - Tìm thấy: [dbo].[projects] trong dòng: "Dòng 3852: INSERT INTO [dbo].[projects] ([workspace_id], [name], [description], [status], [project_type], [start_date], [end_date], [is_archived]) VALUES"
  - Tìm thấy: [dbo].[projects] trong dòng: "Dòng 4854: INSERT INTO [dbo].[projects] ([workspace_id], [name], [description], [status], [project_type], [start_date], [end_date], [is_archived]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 5677: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 6679: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 7681: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 8683: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 9685: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 10687: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 11689: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 12691: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 13693: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 14695: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 15697: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 16699: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 17701: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_members] trong dòng: "Dòng 18703: INSERT INTO [dbo].[project_members] ([project_id], [user_id], [role]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 18924: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 19926: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 20928: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 21930: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 22932: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 23934: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[project_tags] trong dòng: "Dòng 24936: INSERT INTO [dbo].[project_tags] ([project_id], [tag_id]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 24985: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 25987: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 26989: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 27991: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 28993: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 29995: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 30997: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 31999: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 33001: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[task_lists] trong dòng: "Dòng 34003: INSERT INTO [dbo].[task_lists] ([project_id], [name], [position]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 34516: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 35518: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 36520: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 37522: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 38524: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 39526: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 40528: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 41530: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 42532: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 43534: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 44536: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 45538: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 46540: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 47542: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 48544: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 49546: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 50548: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 51550: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 52552: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 53554: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 54556: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 55558: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 56560: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 57562: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 58564: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 59566: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 60568: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 61570: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 62572: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 63574: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 64576: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 65578: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 66580: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 67582: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 68584: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 69586: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 70588: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 71590: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 72592: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 73594: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 74596: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 75598: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 76600: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 77602: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 78604: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 79606: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 80608: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 81610: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 82612: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 83614: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 84616: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 85618: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 86620: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 87622: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 88624: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 89626: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 90628: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 91630: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 92632: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 93634: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 94636: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 95638: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 96640: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 97642: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 98644: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 99646: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 100648: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 101650: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 102652: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 103654: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 104656: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 105658: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 106660: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 107662: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 108664: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"
  - Tìm thấy: [dbo].[tasks] trong dòng: "Dòng 109666: INSERT INTO [dbo].[tasks] ([project_id], [task_list_id], [creator_id], [name], [description], [priority], [status], [end_date]) VALUES"